// Code generated by SQLBoiler 4.4.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Answers      string
	Questions    string
	RevokeTokens string
	Users        string
}{
	Answers:      "answers",
	Questions:    "questions",
	RevokeTokens: "revoke_tokens",
	Users:        "users",
}
